[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    CDN-Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/chart/*"  # TradingView library files
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    CDN-Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"